[feat]: construção do método Inserir.
peris-studio/loja-do-valdir pull request #15
Opened 2024-03-17 23:21 UTC by Hisllaylla

Conforme a issue #8 : 

- Adicionei o método ```Inserir()``` na classe ```Cliente```;
- Coloquei a formatação indicada na estrutura ```DateTime``` > ```DateOnly```, além da atenção ao modificador de acesso ```public```;
- Achei que seria devido fazer um ```public override``` para personalizar o retorno do objeto quando invocado.

![image](https://github.com/peris-studio/loja-do-valdir/assets/73266806/18dcdecd-fdfa-428a-a592-d8db36a20f4c)

2024-03-17 23:39 UTC, jonathanperis requested changes

2024-03-17 23:39 UTC, jonathanperis commented on Models/Cliente.cs
> +    public Cliente Inserir(string Nome, string Sobrenome, int Idade, char Sexo, DateOnly DataNascimento)
Tudo certo aqui, apenas por convecção, argumentos devem ter seus nomes começando com a letra minúscula. Apenas propriedades tem nomes começando com maiúscula.

2024-03-17 23:40 UTC, jonathanperis commented
Parabéns pela aplicação ao override `.ToString();`! Será de bom uso no futuro.

2024-03-17 23:44 UTC, Hisllaylla commented on Models/Cliente.cs
> +    public Cliente Inserir(string Nome, string Sobrenome, int Idade, char Sexo, DateOnly DataNascimento)
Corrigido!

2024-03-17 23:54 UTC, jonathanperis requested changes

2024-03-17 23:54 UTC, jonathanperis commented on Models/Cliente.cs
> +            Nome = Nome,
As propriedades passaram a receber o próprio valor. Não estão utilizando dos valores dos parâmetros. O correto seria: `Nome = nome,`. O mesmo vale para as propriedades restantes.

2024-03-18 00:23 UTC, Hisllaylla commented on Models/Cliente.cs
> +            Nome = Nome,
Feito.

2024-03-18 00:30 UTC, jonathanperis approved these changes

2024-03-18 00:31 UTC, merged